dist: bionic
os:
 - linux
language: shell
services: docker
env:
- HHVM_VERSION=3.30-latest
- HHVM_VERSION=4.1-latest
- HHVM_VERSION=4.2-latest
- HHVM_VERSION=4.6-latest
- HHVM_VERSION=4.10-latest
- HHVM_VERSION=4.14-latest
- HHVM_VERSION=4.18-latest
- HHVM_VERSION=4.22-latest
- HHVM_VERSION=4.25-latest
- HHVM_VERSION=4.26-latest
- HHVM_VERSION=4.30-latest
- HHVM_VERSION=4.34-latest
- HHVM_VERSION=4.38-latest
- HHVM_VERSION=4.42-latest
- HHVM_VERSION=latest
- HHVM_VERSION=nightly


install:
- docker pull hhvm/hhvm:$HHVM_VERSION
script:
- docker run --rm -w /var/source -v $(pwd):/var/source hhvm/hhvm:$HHVM_VERSION ./.travis.sh
